title: David Zhao's APCSA Final Project
author: David Zhao
email: dzhao@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my website that I made for the APCSA final project

# social links
instagram_username: dzhao0488
github_username: dzhaoebnet

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
